[package]
authors = ["clux <sszynrae@gmail.com>"]
name = "dieselpgcrate"
version = "1.0.4"

[dependencies]
openssl = "*"

pq-sys = { version = "0.4.*", features = ["pkg-config"] }
diesel = { version = "1.4.*", features = ["postgres"] }
diesel_migrations = "1.4.*"
